apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"foo-service","namespace":"default"},"spec":{"ports":[{"port":5678,"targetPort":8080}],"selector":{"app":"http-echo"},"type":"LoadBalancer"}}
    metallb.io/ip-allocated-from-pool: kind-pool
  creationTimestamp: "2025-02-11T09:53:06Z"
  name: foo-service
  namespace: default
  resourceVersion: "13154"
  uid: 2c2b662b-7e8a-4dc5-8ad7-9fbc1226c476
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.168.142
  clusterIPs:
  - 10.96.168.142
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30701
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-echo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.18.255.1
      ipMode: VIP
